### ISSUE TITLE
VersionRestController class file has different name

### ISSUE THREAD

**Issue by AxelCB** [AxelCB/DSA-AdminDesafios#1]
VersionRestController class is defined in AppRestController which causes a compile time error in the app, causing the backend to be unable to start. Which should be the right change? Class name or file name?

**Comment by mokocchi** [comment]
I think VersionRestContoller is easier to understand because that's all it does. If another method is added, we can revert the name to AppRestController at that time. The URI will be the same.
Change the file name.

**Comment by AxelCB** [comment]
Fixed in #5
