### ISSUE TITLE
Get Categories is not working

### ISSUE THREAD

**Issue by AxelCB** [AxelCB/DSA-AdminDesafios#2]
Having previously manually loaded some categories in the database, the endpoint is not returning any category in the list.

**Comment by mokocchi** [comment]
Does it return an empty list ( `[]` ) with 200 OK or some kind of error code? (mine is working)
Try these categories
```sql
INSERT INTO category (id, name) VALUES (3, 'forensia');
INSERT INTO category (id, name) VALUES (4, 'inyección');
INSERT INTO category (id, name) VALUES (5, 'criptografía');
```
and this url
`http://localhost:8080/api/categories` (change the port if needed)

It should return

```json
[
    {
        "id": 3,
        "name": "forensia"
    },
    {
        "id": 4,
        "name": "inyección"
    },
    {
        "id": 5,
        "name": "criptografía"
    }
]
```

**Comment by AxelCB** [comment]
You're right, the bug is not about the Category Listing. The problem is more critical:
The server is dropping all tables on restart or shutdown. Hence, even if you insert anything, if you restart, you lose all data.

**Comment by AxelCB** [comment]
This was fixed with the recent modifications in configuration files in merge request #6
