### ISSUE TITLE
Replace Request Mapping anotations

### ISSUE THREAD

**Issue by AxelCB** [AxelCB/DSA-AdminDesafios#4]
We could consider replacing our current @RequestMapping annotations with the method specific ones, such as @GetMapping, @DeleteMapping.

Haven't really investigated a lot, may have problems or not be the best solution

**Comment by mokocchi** [comment]
`@GetMapping` etc are shortcuts of `@RequestMapping` and have the same functionality. 
`@GetMapping` does not support the `consumes` attribute (accepted content-type specification)
Source: http://stackoverflow.com/questions/39077787/difference-between-the-annotations-getmapping-and-requestmappingmethod-requ

`consumes` attribute may be useful on file uploading for challenges later (I'm not really sure)

**Comment by AxelCB** [comment]
Okay, then it's okay and doesn't need to be modified. Closing the issue
