### ISSUE TITLE
quick fix - bad refactoring

### ISSUE THREAD

**Issue by mokocchi** [AxelCB/DSA-AdminDesafios#40]
Here
Backend/src/main/java/ar/edu/unlp/dsa/controller/AuthRestController.java
at lines 28, 39 and 49
```"http://localhost:"+Application.FRONTEND_PORT``` should be ```Application.FRONTEND_URL```.
The refactoring was made before the merge so I forgot to fix this.

**Comment by AxelCB** [comment]
Closing this issue since it was fixed by merge request #41
